### ISSUE TITLE
How to use file-box in node

### ISSUE THREAD

**Issue by lijiarui** [zixia/file-box#2]
### Issue description
When using fromStream, it says `TypeError: FileBox.fromStream is not a function`

### Reproduce
I use node instead of typescript,code as follows:
```js
const FileBox = require('file-box')
const path = require('path')
const fs = require('fs')
const BOT_QR_CODE_IMAGE_FILE = path.resolve(
  __dirname,
  '../docs/bot-qr-code.png',
)
const fileBox = FileBox.fromStream(
  fs.createReadStream(BOT_QR_CODE_IMAGE_FILE),
  BOT_QR_CODE_IMAGE_FILE,
)
```

### Error Log
```shell
/Users/jiaruili/git/wechaty-getting-started/examples/test.js:9
const fileBox = require('file-box').fromStream(
                                    ^

TypeError: require(...).fromStream is not a function
    at Object.<anonymous> (/Users/jiaruili/git/wechaty-getting-started/examples/test.js:9:37)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by zixia** [comment]
Please read the latest doc before is l use it.
